plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tapkill'
    compileSdk 34
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId 'com.tapkill'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // تعطيل AAPT2 والاعتماد على AAPT القديم
    aaptOptions {
        useAapt2 = false
    }
}
